GM.Config = GM.Config or {}
GM.Config.Generic = GM.Config.Generic or {}

local config = GM.Config.Generic
config.DEFAULT_PLAYER_MODEL = "models/player/odessa.mdl"

config.PLAYER_MODELS = {
    "models/player/odessa.mdl",
    "models/player/alyx.mdl",
    "models/player/barney.mdl",
    "models/player/breen.mdl",
    "models/player/p2_chell.mdl",
    "models/player/eli.mdl",
    "models/player/group01/female_01.mdl",
    "models/player/group01/female_02.mdl",
    "models/player/group01/female_03.mdl",
    "models/player/group01/female_04.mdl",
    "models/player/group01/female_05.mdl",
    "models/player/group01/female_06.mdl",
    "models/player/group03/female_01.mdl",
    "models/player/group03/female_02.mdl",
    "models/player/group03/female_03.mdl",
    "models/player/group03/female_04.mdl",
    "models/player/group03/female_05.mdl",
    "models/player/group03/female_06.mdl",
    "models/player/gman_high.mdl",
    "models/player/hostage/hostage_01.mdl",
    "models/player/hostage/hostage_02.mdl",
    "models/player/hostage/hostage_03.mdl",
    "models/player/hostage/hostage_04.mdl",
    "models/player/kleiner.mdl",
    "models/player/magnusson.mdl",
    "models/player/group01/male_01.mdl",
    "models/player/group01/male_02.mdl",
    "models/player/group01/male_03.mdl",
    "models/player/group01/male_04.mdl",
    "models/player/group01/male_05.mdl",
    "models/player/group01/male_06.mdl",
    "models/player/group01/male_07.mdl",
    "models/player/group01/male_08.mdl",
    "models/player/group01/male_09.mdl",
    "models/player/group03/male_01.mdl",
    "models/player/group03/male_02.mdl",
    "models/player/group03/male_03.mdl",
    "models/player/group03/male_04.mdl",
    "models/player/group03/male_05.mdl",
    "models/player/group03/male_06.mdl",
    "models/player/group03/male_07.mdl",
    "models/player/group03/male_08.mdl",
    "models/player/group03/male_09.mdl",
    "models/player/group03m/male_01.mdl",
    "models/player/group03m/male_02.mdl",
    "models/player/group03m/male_03.mdl",
    "models/player/group03m/male_04.mdl",
    "models/player/group03m/male_05.mdl",
    "models/player/group03m/male_06.mdl",
    "models/player/group03m/male_07.mdl",
    "models/player/group03m/male_08.mdl",
    "models/player/group03m/male_09.mdl",
    "models/player/group03m/female_01.mdl",
    "models/player/group03m/female_02.mdl",
    "models/player/group03m/female_03.mdl",
    "models/player/group03m/female_04.mdl",
    "models/player/group03m/female_05.mdl",
    "models/player/group03m/female_06.mdl",
    "models/player/monk.mdl",
    "models/player/mossman.mdl",
    "models/player/mossman_arctic.mdl",
    "models/player/group02/male_02.mdl",
    "models/player/group02/male_04.mdl",
    "models/player/group02/male_06.mdl",
    "models/player/group02/male_08.mdl"
}
